query {
    result: Balances(
        filter: $filter,
        pagination: $pagination
    ) {
        items {
            ...Balance
        }
        cursor {
            ...PaginationCursor
        }
    }
}

$filter: BalanceFilter
$pagination: PaginationInput = { page: 1, limit: 100 }
