query {
    result: Transactions(
        filter: $filter
        sort: $sort
        pagination: $pagination
    ) {
        items {
            ...TransactionFragment
        }
        cursor {
            ...PaginationCursorFragment
        }
    }
}

$filter: TransactionFilter
$sort: TransactionSortInput
$pagination: PaginationInput = { page: 1, limit: 100 }
