query {
    result: Transactions(
        filter: $filter
        sort: $sort
        pagination: $pagination
    ) {
        ...TransactionFragment
    }
}

$filter: TransactionFilter
$sort: TransactionSortInput
$pagination: PaginationInput = { page: 1, limit: 100 }
