fragment TransactionFragment on EnjinTransaction {
    id
    transactionId
    title @include(if: $withMeta)
    contract @include(if: $withMeta)
    encodedData @include(if: $withEncodedData)
    type
    icon @include(if: $withMeta)
    value @include(if: $withTokenData)
    signedTransaction @include(if: $withSignedTxs)
    signedBackupTransaction @include(if: $withSignedTxs)
    signedCancelTransaction @include(if: $withSignedTxs)
    error @include(if: $withError)
    nonce @include(if: $withNonce)
    retryState @include(if: $withState)
    state @include(if: $withState)
    accepted @include(if: $withState)
    receipt @include(if: $withReceipt)
    tokenId @include(if: $withTokenData)
    createdAt @include(if: $withRequestTimestamps)
    updatedAt @include(if: $withRequestTimestamps)
}

$withMeta: Boolean = false
$withEncodedData: Boolean = false
$withTokenData: Boolean = false
$withSignedTxs: Boolean = false
$withError: Boolean = false
$withNonce: Boolean = false
$withState: Boolean = false
$withReceipt: Boolean = false
$withRequestTimestamps: Boolean = false
