query {
    result: EnjinWallet(
        ethAddress: $ethAddr
    ) {
        items {
            ...WalletFragment
        }
        cursor {
            ...PaginationCursorFragment
        }
    }
}

$ethAddr: String