fragment WalletFragment on EnjinWallet {
    ethAddress
    enjAllowance
    enjBalance
    ethBalance
    tokensCreated @include(if: $withTokensCreated) {
        ...TokenFragment
    }
    createdAt @include(if: $withWalletTimestamps)
    updatedAt @include(if: $withWalletTimestamps)
}

$withTokensCreated: Boolean = false
$withWalletTimestamps: Boolean = false
