query {
    result: Transactions(
        filter: $filter
        sort: $sort
        pagination: $pagination
    ) {
        items {
            ...Transaction
        }
        cursor {
            ...PaginationCursor
        }
    }
}

$filter: TransactionFilter
$sort: TransactionSortInput
$pagination: PaginationInput
