query {
    result: Tokens(
        filter: $filter,
        sort: $sort,
        pagination: $pagination
    ) {
        items {
            ...Token
        }
        cursor {
            ...PaginationCursor
        }
    }
}

$filter: TokenFilter
$sort: TokenSortInput
$pagination: PaginationInput
