query {
    result: Tokens(
        filter: $filter,
        sort: $sort,
        pagination: $pagination
    ) {
        items {
            ...TokenFragment
        }
        cursor {
            ...PaginationCursorFragment
        }
    }
}

$filter: TokenFilter
$sort: TokenSortInput
$pagination: PaginationInput = { page: 1, limit: 100 }
