fragment Token on EnjinToken {
    id(format: $tokenIdFormat)
    name
    blockHeight @include(if: $withTokenBlocks)
    creator @include(if: $withCreator)
    firstBlock @include(if: $withTokenBlocks)
    meltFeeRatio @include(if: $withMeltDetails)
    meltFeeMaxRatio @include(if: $withMeltDetails)
    meltValue @include(if: $withMeltDetails)
    metadata @include(if: $withMetadata)
    metadataURI @include(if: $withMetadataURI)
    nonFungible
    reserve @include(if: $withSupplyDetails)
    supplyModel @include(if: $withSupplyDetails)
    circulatingSupply @include(if: $withSupplyDetails)
    mintableSupply @include(if: $withSupplyDetails)
    totalSupply @include(if: $withSupplyDetails)
    transferable @include(if: $withTransferSettings)
    transferFeeSettings @include(if: $withTransferSettings) {
        ...TokenTransferFeeSettings
    }
    variantMode @include(if: $withTokenVariantMode)
    variants @include(if: $withTokenVariants) {
        ...TokenVariant
    }
    createdAt @include(if: $withTokenTimestamps)
    updatedAt @include(if: $withTokenTimestamps)
}

$tokenIdFormat: TokenIdFormat
$withTokenBlocks: Boolean = false
$withCreator: Boolean = false
$withMeltDetails: Boolean = false
$withMetadata: Boolean = false
$withMetadataURI: Boolean = false
$withSupplyDetails: Boolean = false
$withTransferSettings: Boolean = false
$withTokenVariantMode: Boolean = false
$withTokenVariants: Boolean = false
$withTokenTimestamps: Boolean = false
