fragment TokenVariant on EnjinTokenVariant {
    id
    tokenId
    variantMetadata @include(if: $withVariantMetadata)
    usageCount
    createdAt @include(if: $withVariantTimestamps)
    updatedAt @include(if: $withVariantTimestamps)
}

$withVariantMetadata: Boolean = false
$withVariantTimestamps: Boolean = false
