query {
    result: Players(
        filter: $filter
        pagination: $pagination
    ) {
        items {
            ...Player
        }
        cursor {
            ...PaginationCursor
        }
    }
}

$filter: PlayerFilter
$pagination: PaginationInput
