fragment AppFragment on EnjinApp {
    id
    secret @include(if: $withSecret)
    name
    description
    image
    linkingCode @include(if: $withLinkingCode)
    linkingCodeQr(size: $linkingCodeQrSize) @include(if: $withLinkingCodeQr)
    tokenCount @include(if: $withTokenCount)
    owner @include(if: $withOwner) {
        id
    }
    identities @include(if: $withAppUserIdentities) {
        ...IdentityFragment
    }
    identity @include(if: $withCurrentUserIdentity) {
        ...IdentityFragment
    }
    transactions @include(if: $withAppTransactions) {
        ...TransactionFragment
    }
    tokens @include(if: $withAppTokens) {
        ...TokenFragment
    }
    wallets @include(if: $withAppWallets) {
        ...WalletFragment
    }
    createdAt @include(if: $withAppTimestamps)
    updatedAt @include(if: $withAppTimestamps)
}

$withSecret: Boolean = false
$withLinkingCode: Boolean = false
$withLinkingCodeQr: Boolean = false
$linkingCodeQrSize: Int
$withAppUserIdentities: Boolean = false
$withCurrentUserIdentity: Boolean = false
$withOwner: Boolean = false
$withTokenCount: Boolean = false
$withAppTransactions: Boolean = false
$withAppTokens: Boolean = false
$withAppWallets: Boolean = false
$withAppTimestamps: Boolean = false