fragment AppFragment on EnjinApp {
    id
    name
    description
    image
    linkingCode @include(if: $withLinkingCode)
    linkingCodeQr(size: $linkingCodeQrSize) @include(if: $withLinkingCodeQr)
    createdAt @include(if: $withAppTimestamps)
    updatedAt @include(if: $withAppTimestamps)
}

$withLinkingCode: Boolean = false
$withLinkingCodeQr: Boolean = false
$linkingCodeQrSize: Int
$withAppTimestamps: Boolean = false
