fragment AppFragment on EnjinApp {
    id
    secret @include(if: $withSecret)
    name
    description
    image
    linkingCode @include(if: $withLinkingCode)
    linkingCodeQr(size: $linkingCodeQrSize) @include(if: $withLinkingCodeQr)
    tokenCount @include(if: $withTokenCount)
    owner @include(if: $withOwner) {
        id
    }
    identities @include(if: $withUserIdentities) {
        ...IdentityFragment
    }
    identity @include(if: $withCurrentUserIdentity) {
        ...IdentityFragment
    }
    transactions @include(if: $withTransactions) {
        ...TransactionFragment
    }
    tokens @include(if: $withTokens) {
        ...TokenFragment
    }
    wallets @include(if: $withWallets) {
        ...WalletFragment
    }
    createdAt @include(if: $withAppTimestamps)
    updatedAt @include(if: $withAppTimestamps)
}

$withSecret: Boolean = false
$withLinkingCode: Boolean = false
$withLinkingCodeQr: Boolean = false
$linkingCodeQrSize: Int
$withUserIdentities: Boolean = false
$withCurrentUserIdentity: Boolean = false
$withOwner: Boolean = false
$withTokenCount: Boolean = false
$withTransactions: Boolean = false
$withTokens: Boolean = false
$withWallets: Boolean = false
$withAppTimestamps: Boolean = false