query {
    result: Players(
        filter: $filter
        pagination: $pagination
    ) {
        items {
            ...PlayerFragment
        }
        cursor {
            ...PaginationCursorFragment
        }
    }
}

$filter: PlayerFilter
$pagination: PaginationInput = { page: 1, limit: 100 }
