query {
    result: Players(
        filter: $filter
        pagination: $pagination
    ) {
        items {
            ...Player
        }
        cursor {
            ...PaginationCursor
        }
    }
}

$filter: PlayerFilter
$pagination: PaginationInput = { page: 1, limit: 100 }
