fragment Balance on EnjinBalance {
    id(format: $balIdFormat)
    index(format: $balIndexFormat)
    value
    app @include(if: $withBalAppId) {
        id
    }
    wallet @include(if: $withBalWalletAddress) {
        ethAddress
    }
}

$balIdFormat: TokenIdFormat
$balIndexFormat: TokenIndexFormat
$withBalAppId: Boolean = false
$withBalWalletAddress: Boolean = false
