fragment Wallet on EnjinWallet {
    ethAddress
    enjAllowance
    enjBalance
    ethBalance
    tokensCreated @include(if: $withTokensCreated) {
        ...Token
    }
}

$withTokensCreated: Boolean = false
