fragment IdentityFragment on EnjinIdentity {
    id
    appId
    linkingCode @include(if: $withLinkingCode)
    linkingCodeQr(size: $linkingCodeQrSize) @include(if: $withLinkingCodeQr)
    app @include(if: $withIdentityApp) {
        ...AppFragment
    }
    user @include(if: $withIdentityUser) {
        ...UserFragment
    }
    wallet @include(if: $withIdentityWallet) {
        ...WalletFragment
    }
    createdAt @include(if: $withIdentityTimestamps)
    updatedAt @include(if: $withIdentityTimestamps)
}

$withLinkingCode: Boolean = false
$withLinkingCodeQr: Boolean = false
$linkingCodeQrSize: Int
$withIdentityApp: Boolean = false
$withIdentityUser: Boolean = false
$withIdentityWallet: Boolean = false
$withIdentityTimestamps: Boolean = false