fragment IdentityFragment on EnjinIdentity {
    id
    appId
    linkingCode @include(if: $withLinkingCode)
    linkingCodeQr(size: $linkingCodeQrSize) @include(if: $withLinkingCodeQr)
    app @include(if: $withApp) {
        ...AppFragment
    }
    user @include(if: $withUser) {
        ...UserFragment
    }
    transactions(
        state: $transactionsState,
        state_in: $transactionsStateIn,
        can_broadcast_only: $transactionsCanBroadcastOnly,
        pagination: $transactionsPagination,
        sort_by: $transactionsSortBy
    ) @include(if: $withTransactions) {
        ...TransactionFragment
    }
    tokens(
        id: $tokensId,
        index: $tokensIndex,
        pagination: $tokensPagination,
        sort_by: $tokensSortBy
    ) @include(if: $withTokens) {
        ...TokenFragment
    }
    wallet @include(if: $withWallet) {
        ...WalletFragment
    }
    createdAt @include(if: $withIdentityTimestamps)
    updatedAt @include(if: $withIdentityTimestamps)
}

$withLinkingCode: Boolean = false
$withLinkingCodeQr: Boolean = false
$linkingCodeQrSize: Int
$withApp: Boolean = false
$withUser: Boolean = false
$withTransactions: Boolean = false
$transactionsState: TransactionState
$transactionsStateIn: [TransactionState]
$transactionsCanBroadcastOnly: Boolean
$transactionsPagination: PaginationInput
$transactionsSortBy: TransactionSortInput
$withTokens: Boolean = false
$tokensId: String
$tokensIndex: String
$tokensPagination: PaginationInput
$tokensSortBy: TokenSortInput
$withWallet: Boolean = false
$withIdentityTimestamps: Boolean = false