fragment UserFragment on EnjinUser {
    id
    name
    accessTokens @include(if: $withUserAccessTokens)
    isPlayer
    emailVerified
    app(id: $userAppId) @include(if: $withUserApp) {
        ...AppFragment
    }
    createdAt @include(if: $withUserTimestamps)
    updatedAt @include(if: $withUserTimestamps)
}

$withUserAccessTokens: Boolean = false
$withUserApp: Boolean = false
$userAppId: Int
$withUserTimestamps: Boolean = false