fragment UserFragment on EnjinUser {
    id
    name
    accessTokens @include(if: $withUserAccessTokens)
    isPlayer
    emailVerified
    app(id: $appId) @include(if: $withUserApps) {
        ...AppFragment
    }
    apps(id: $appId) @include(if: $withUserApps) {
        ...AppFragment
    }
    identities @include(if: $withUserIdentities) {
        ...IdentityFragment
    }
    createdAt @include(if: $withUserTimestamps)
    updatedAt @include(if: $withUserTimestamps)
}

$appId: Int
$withUserAccessTokens: Boolean = false
$withUserIdentities: Boolean = false
$withUserTimestamps: Boolean = false